# java-app/src/main/resources/application.properties
server.port=8080
spring.application.name=obs-service

# Actuator
management.endpoints.web.exposure.include=prometheus,health,info
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

# Evitar errores de recursos estáticos
spring.web.resources.add-mappings=false