# application.properties
server.port=8080
spring.application.name=obs-service

# Exponer endpoints de actuator
management.endpoints.web.exposure.include=prometheus,health,info
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

# Evitar que Spring maneje /metrics como recurso estático
spring.web.resources.add-mappings=false


# abilitar histogramas para métricas HTTP
management.metrics.distribution.percentiles-histogram.http.server.requests=true

# Opcional: Definir buckets específicos para mejor precisión
management.metrics.distribution.sla.http.server.requests=10ms,50ms,100ms,250ms,500ms,1s,2s,5s

# Mantener exposición de Prometheus
management.endpoints.web.exposure.include=prometheus,health,info
management.endpoint.prometheus.enabled=true